= thrempl

image:https://img.shields.io/badge/babashka-compatible-brightgreen["Babashka", link="https://github.com/babashka/babashka"]
image:https://img.shields.io/badge/nbb-compatible-brightgreen["nbb", link="https://github.com/babashka/nbb"]

A proof of concept for simple template engine using threading macros.

== Concept

* Similar mustache, but threading macro
** `{{-> v f (g "foo")}}`
** `{{->> v f (g "foo")}}`
* No dependencies

== Example

[source,clojure]
----
(require '[thrempl.core :as thrempl])
;; => nil

(thrempl/render "{{-> name greet}}!"
                {:name "world" :greet #(str "Hello " %)})
;; => "Hello world!"

(thrempl/render "{{->> name (str \"Hello \")}}!"
                {:name "world" :str str})
;; => "Hello world!"
----

== License

Copyright © 2022 https://twitter.com/uochan[Masashi Iizuka]

This program and the accompanying materials are made available under the
terms of the Eclipse Public License 2.0 which is available at
http://www.eclipse.org/legal/epl-2.0.

This Source Code may also be made available under the following Secondary
Licenses when the conditions for such availability set forth in the Eclipse
Public License, v. 2.0 are satisfied: GNU General Public License as published by
the Free Software Foundation, either version 2 of the License, or (at your
option) any later version, with the GNU Classpath Exception which is available
at https://www.gnu.org/software/classpath/license.html.
